"""HTTP delivery policy for application error codes."""

from __future__ import annotations

from typing import Final

from starlette import status

from app.errors import ErrorCode

HTTP_STATUS_BY_ERROR_CODE: Final[dict[ErrorCode, int]] = {
    ErrorCode.REQUEST_VALIDATION_FAILED: status.HTTP_422_UNPROCESSABLE_CONTENT,
    ErrorCode.EMPTY_UPDATE: status.HTTP_422_UNPROCESSABLE_CONTENT,
    ErrorCode.UNSUPPORTED_UPLOAD_TYPE: status.HTTP_415_UNSUPPORTED_MEDIA_TYPE,
    ErrorCode.FILE_TOO_LARGE: status.HTTP_413_CONTENT_TOO_LARGE,
    ErrorCode.TEXT_LINE_TOO_LARGE: status.HTTP_422_UNPROCESSABLE_CONTENT,
    ErrorCode.UNSAFE_PATH: status.HTTP_400_BAD_REQUEST,
    ErrorCode.NO_MODELS: status.HTTP_409_CONFLICT,
    ErrorCode.MODEL_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.MODEL_STORE_INVALID: status.HTTP_500_INTERNAL_SERVER_ERROR,
    ErrorCode.ACTIVE_MODEL_NOT_SET: status.HTTP_409_CONFLICT,
    ErrorCode.ACTIVE_INSTRUCTION_SET_NOT_SET: status.HTTP_409_CONFLICT,
    ErrorCode.SETTINGS_STORE_INVALID: status.HTTP_500_INTERNAL_SERVER_ERROR,
    ErrorCode.MODEL_ENDPOINT_NOT_CONFIGURED: status.HTTP_409_CONFLICT,
    ErrorCode.TOKEN_COUNT_FAILED: status.HTTP_502_BAD_GATEWAY,
    ErrorCode.MODEL_INPUT_LIMIT_EXCEEDED: status.HTTP_422_UNPROCESSABLE_CONTENT,
    ErrorCode.MODEL_OUTPUT_LIMIT_EXCEEDED: status.HTTP_409_CONFLICT,
    ErrorCode.MODEL_CONTEXT_LIMIT_EXCEEDED: status.HTTP_422_UNPROCESSABLE_CONTENT,
    ErrorCode.VISION_NOT_SUPPORTED: status.HTTP_409_CONFLICT,
    ErrorCode.AUDIO_NOT_SUPPORTED: status.HTTP_409_CONFLICT,
    ErrorCode.PDF_DEPENDENCY_MISSING: status.HTTP_503_SERVICE_UNAVAILABLE,
    ErrorCode.FFMPEG_UNAVAILABLE: status.HTTP_503_SERVICE_UNAVAILABLE,
    ErrorCode.DOCX_PROCESSOR_MISSING: status.HTTP_503_SERVICE_UNAVAILABLE,
    ErrorCode.DOCX_PROCESSOR_BUSY: status.HTTP_503_SERVICE_UNAVAILABLE,
    ErrorCode.DOCX_UNSUPPORTED_FEATURE: status.HTTP_422_UNPROCESSABLE_CONTENT,
    ErrorCode.DOCX_PROCESSING_FAILED: status.HTTP_500_INTERNAL_SERVER_ERROR,
    ErrorCode.DOCUMENT_CONVERTER_MISSING: status.HTTP_503_SERVICE_UNAVAILABLE,
    ErrorCode.DOCUMENT_CONVERSION_FAILED: status.HTTP_500_INTERNAL_SERVER_ERROR,
    ErrorCode.PROMPT_MISSING: status.HTTP_500_INTERNAL_SERVER_ERROR,
    ErrorCode.UNSUPPORTED_PROMPT_KIND: status.HTTP_501_NOT_IMPLEMENTED,
    ErrorCode.INSTRUCTION_SET_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.INVALID_INSTRUCTION_SET: status.HTTP_422_UNPROCESSABLE_CONTENT,
    ErrorCode.INSTRUCTION_SET_EXISTS: status.HTTP_409_CONFLICT,
    ErrorCode.INSTRUCTION_SET_CONFLICT: status.HTTP_409_CONFLICT,
    ErrorCode.INSTRUCTION_SET_NOT_LOCKED: status.HTTP_409_CONFLICT,
    ErrorCode.INSTRUCTION_SET_INTEGRITY_ERROR: status.HTTP_500_INTERNAL_SERVER_ERROR,
    ErrorCode.SESSION_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.SESSION_FILE_MISSING: status.HTTP_500_INTERNAL_SERVER_ERROR,
    ErrorCode.SOURCE_INTEGRITY_ERROR: status.HTTP_500_INTERNAL_SERVER_ERROR,
    ErrorCode.ANALYSIS_ALREADY_RUNNING: status.HTTP_409_CONFLICT,
    ErrorCode.PROVIDER_CONNECTION_FAILED: status.HTTP_502_BAD_GATEWAY,
    ErrorCode.PROVIDER_MODEL_NOT_FOUND: status.HTTP_502_BAD_GATEWAY,
    ErrorCode.PROVIDER_AUTHENTICATION_FAILED: status.HTTP_502_BAD_GATEWAY,
    ErrorCode.PROVIDER_RATE_LIMITED: status.HTTP_503_SERVICE_UNAVAILABLE,
    ErrorCode.PROVIDER_REQUEST_INVALID: status.HTTP_502_BAD_GATEWAY,
    ErrorCode.PROVIDER_RESPONSE_INVALID: status.HTTP_502_BAD_GATEWAY,
    ErrorCode.NOT_PDF_SESSION: status.HTTP_422_UNPROCESSABLE_CONTENT,
    ErrorCode.PDF_PAGE_OUT_OF_RANGE: status.HTTP_422_UNPROCESSABLE_CONTENT,
    ErrorCode.INVALID_DOCX_TEXT_TARGET: status.HTTP_422_UNPROCESSABLE_CONTENT,
    ErrorCode.FINDING_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.LAYER_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.INVALID_FINDING_UPDATE: status.HTTP_422_UNPROCESSABLE_CONTENT,
    ErrorCode.INVALID_LAYER_UPDATE: status.HTTP_422_UNPROCESSABLE_CONTENT,
    ErrorCode.DUPLICATE_FINDING_LAYER: status.HTTP_409_CONFLICT,
    ErrorCode.INVALID_ACTION_EFFECT: status.HTTP_422_UNPROCESSABLE_CONTENT,
    ErrorCode.OUTPUT_MISSING: status.HTTP_404_NOT_FOUND,
    ErrorCode.OUTPUT_STATE_CHANGED: status.HTTP_409_CONFLICT,
    ErrorCode.OUTPUT_BLOCKED_PENDING_REVIEW: status.HTTP_409_CONFLICT,
    ErrorCode.AUDIO_RENDER_FAILED: status.HTTP_500_INTERNAL_SERVER_ERROR,
    ErrorCode.EXPORT_MISSING: status.HTTP_404_NOT_FOUND,
    ErrorCode.REVIEW_INTEGRITY_ERROR: status.HTTP_500_INTERNAL_SERVER_ERROR,
    ErrorCode.INTERNAL_ERROR: status.HTTP_500_INTERNAL_SERVER_ERROR,
}

if set(HTTP_STATUS_BY_ERROR_CODE) != set(ErrorCode):
    raise RuntimeError("HTTP status policy must cover every application error code.")


def http_status_for(code: ErrorCode) -> int:
    """Return the explicit HTTP status assigned to an application error code."""
    return HTTP_STATUS_BY_ERROR_CODE[code]
